/**
 * 
 */
package com.palmyrasyscorp.db.common;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * @author Prem
 *
 */
public class ProxyDbStatement {

	private static Log log = LogFactory.getLog(TestTable.class);
	
	/**
	 * 
	 */
	private ProxyDbConnection m_conn;

	/**
	 * 
	 */
	private Statement m_stmt;
	
	/**
	 * 
	 *
	 */
	protected ProxyDbStatement() {
		super();
	}
	
	/**
	 * 
	 * @param stmt
	 */
	public ProxyDbStatement(Statement stmt) {
		m_stmt = stmt;
	}
	
	/**
	 * 
	 * @param qry
	 * @return
	 */
	public ProxyDbResultSet executeQuery(String qry) {
		ProxyDbResultSet ret = null;
		
		try {
			ResultSet rs = m_stmt.executeQuery(qry);
			ret = new ProxyDbResultSet(rs);
		} catch (SQLException e) {
			handleException(e);
		}
		
		return (ret);
	}
	
	/**
	 * 
	 * @param qry
	 * @return
	 */
	public boolean execute(String qry) {
		boolean ret = false;
		
		try {
			ret = m_stmt.execute(qry);
		} catch (SQLException e) {
			handleException(e);
		}
		
		return (ret);
	}
	
	/**
	 * 
	 * @param qry
	 * @return
	 */
	public int executeUpdate(String sql, int autoGeneratedKeys) {
		int ret = 0;
		
		try {
			ret = m_stmt.executeUpdate(sql, autoGeneratedKeys);
		} catch (SQLException e) {
			handleException(e);
		}
		
		return (ret);
	}
	
	/**
	 * 
	 * @return
	 */
	public ProxyDbResultSet getGeneratedKeys() {
		ProxyDbResultSet ret = null;
		try {
			ResultSet rs = m_stmt.getGeneratedKeys();
			ret = new ProxyDbResultSet(rs);
		} catch (SQLException e) {
			handleException(e);
		}
		return (ret);
	}
	
	/**
	 * 
	 * @param e
	 */
	private void handleException(SQLException e) {
		log.error(null, e);
		m_conn.handleException(e);
	}
	
	/**
	 * 
	 *
	 */
	public void cleanup() {
		try {
			m_stmt.close();
		} catch (SQLException se) {
			handleException(se);
		} catch (Exception e) {			
			log.error(null, e);
		}
		m_stmt = null;
		m_conn = null;
	}
}
