<?xml version="1.0" ?>

<definitions
	name="http://www.palmyrasys.com/webservices/CableAssurance/Cms"
	targetNamespace="http://www.palmyrasys.com/webservices/CableAssurance/Cms"
	xmlns:tns="http://www.palmyrasys.com/webservices/CableAssurance"
	xmlns:tns-cms="http://www.palmyrasys.com/webservices/CableAssurance/Cms"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">

	<import
		namespace="http://www.palmyrasys.com/webservices/CableAssurance"
		location="CableAssurance.xsd" />

	<!-- message declns -->

	<message name="empty" />

	<message name="GetLineStatusRequest">
		<part name="input" type="tns:ArrayOfCMSLineT" />
	</message>
	<message name="GetLineStatusResponse">
		<part name="output" type="tns:ArrayOfCMSLineT" />
	</message>

	<!-- endpoint/port-type declns -->

	<portType name="CmsEP">
		<operation name="getLineStatus">
			<input message="tns-cms:GetLineStatusRequest" />
			<output message="tns-cms:GetLineStatusResponse" />
		</operation>
	</portType>

	<!-- binding declns -->

	<binding name="CmsSOAPBinding" type="tns-cms:CmsEP">
		<soap:binding style="rpc"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="getLineStatus">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="encoded"
					namespace="http://www.palmyrasys.com/webservices/CableAssurance/Cms"
					encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</input>
			<output>
				<soap:body use="encoded"
					namespace="http://www.palmyrasys.com/webservices/CableAssurance/Cms"
					encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
			</output>
		</operation>
	</binding>

	<!-- service decln -->

	<service name="CmsService">
		<port name="CmsEP" binding="tns-cms:CmsSOAPBinding">
			<soap:address
				location="http://localhost:8080/CableAssurance/caservices/CmsEP" />
		</port>
	</service>

</definitions>